# Generated by Django 3.0.3 on 2020-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resourceDiscription',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
