# Generated by Django 3.0.3 on 2020-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_resource_resourcediscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourceDiscription',
            field=models.CharField(max_length=100),
        ),
    ]
