# Generated by Django 3.0.3 on 2020-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20200814_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='AboutImage',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='AboutRole',
            field=models.CharField(default='Captain', max_length=10),
        ),
    ]
