# Generated by Django 3.0.3 on 2020-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20200814_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='AboutPhone',
            field=models.CharField(max_length=10),
        ),
    ]
