# Generated by Django 3.0.3 on 2020-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20200814_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OverDate', models.DateField()),
                ('OverName', models.CharField(max_length=40)),
                ('OverImages', models.URLField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='AboutEmail',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
