# Generated by Django 3.0.3 on 2020-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20200815_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Images', models.URLField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resourceImage',
            new_name='resourceResource',
        ),
    ]
