# Generated by Django 3.1 on 2020-08-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_auto_20200824_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='AboutEmail',
            field=models.EmailField(max_length=50),
        ),
    ]
