# Generated by Django 3.1 on 2020-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_auto_20200824_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Images', models.URLField(unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gal',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='UpcommingEvent',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='Images',
            new_name='CoverImages',
        ),
    ]
