# Generated by Django 3.1 on 2020-09-04 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_auto_20200904_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='Folder',
            field=models.URLField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
