# Generated by Django 3.1 on 2020-09-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_gallery_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Folder',
            new_name='Folders',
        ),
    ]
