# Generated by Django 3.1 on 2020-09-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_auto_20200904_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Events',
        ),
        migrations.DeleteModel(
            name='EventsOver',
        ),
    ]
